version: '3.8'

services:
  kong:
    build: .
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/config/kong.yml"
      # Plugin configuration as per documentation
      KONG_PLUGINSERVER_NAMES: "js"
      KONG_PLUGINSERVER_JS_SOCKET: "/usr/local/kong/js_pluginserver.sock"
      KONG_PLUGINSERVER_JS_START_CMD: "/usr/local/bin/kong-js-pluginserver -v --plugins-directory /usr/local/kong/js-plugins"
      KONG_PLUGINSERVER_JS_QUERY_CMD: "/usr/local/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins"
      KONG_PLUGINS: "bundled,my-custom-plugin"
    volumes:
      - ./config/kong.yml:/opt/kong/config/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge