# docker-compose.yml
version: '3.8'

services:
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/config/kong.yml"
      KONG_LOG_LEVEL: debug
    volumes:
      - ./config/kong.yml:/opt/kong/config/kong.yml:ro
    ports:
      - "8000:8000"  # Proxy port
      - "8001:8001"  # Admin API
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge