_format_version: "2.1"
_transform: true

services:
  - name: service-one
    url: http://host.docker.internal:3000
    routes:
      - name: service-one-route
        paths:
          - /service1

  - name: service-two
    url: http://host.docker.internal:3001
    routes:
      - name: service-two-route
        paths:
          - /service2

plugins:
  - name: request-termination
    config:
      status_code: 403
      message: So long and thanks for all the fish!
      trigger: "q"
