_format_version: "2.1"
_transform: true

services:
  - name: service-one
    url: http://host.docker.internal:3000
    routes:
      - name: service-one-route
        paths:
          - /service1
        plugins:
          - name: cors
            config:
              origins:
                - "http://info.cern.ch"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - "*"
              exposed_headers:
                - "*"

  - name: service-two
    url: http://host.docker.internal:3001
    routes:
      - name: service-two-route
        paths:
          - /service2

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - "*"
      exposed_headers:
        - "*"

  - name: rate-limiting
    config:
      minute: 5
      policy: redis
      redis_host: "kong-redis"
      redis_port: 6379
      redis_timeout: 2000
      fault_tolerant: true
      hide_client_headers: false # Make headers visible
